DROP TABLE IF EXISTS public; 
DROP TABLE IF EXISTS public_vote;
DROP TABLE IF EXISTS public_party;
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS party;
DROP TABLE IF EXISTS candidate;
DROP TABLE IF EXISTS election;